### ISSUE TITLE
0018: Worker: Tackle FTP protocol

### ISSUE THREAD

**Issue by earthquakesan** [dice-group/Squirrel#1]
Worker should be able to download dumps from FTP servers.

Comment from Micha: "during the last days, I saw at least one example for a dump with a FTP URI."

**Comment by MichaelRoeder** [comment]
Did this "Micha" provided an example URI? :smile:

**Comment by MichaelRoeder** [comment]
We are missing a good way to test this, i.e., a mock FTP server would be good for JUnit tests.
