### ISSUE TITLE
Implement a domain-based queue

### ISSUE THREAD

**Issue by MichaelRoeder** [dice-group/Squirrel#101]
## Description

As the user of a crawler, I would like to crawl as much as possible in parallel. The owner of a server would like to give his service to many different costumers in parallel (and don't want to be blocked by a single client). Both goals are contradicting and in the worst case, a crawler can be blocked by a certain server.

Until now, we are using an IP-based system for making sure that only one single worker is talking to a server. However, this might be too restrictive and a domain-based approach (i.e., one worker is responsible for a single domain regardless whether the domain shares the IP with another domain) might be better.

## Steps

- [x] investigate the best practices regarding this issue.
    - How are different crawlers handling this issue?
    - What is the exact meaning of a robots.txt file, i.e., does it hold only for a single domain?
    - What about sub-domains? Do they count as part of their super domain?
- [x] implement a domain-based queue that can be used instead of the ip-based queue

**Comment by gsjunior86** [comment]
In comparsion with other crawlers, i found that Bing bot uses the subdomain in the highest level of the queue (https://searchengineland.com/bing-crawling-indexing-and-rendering-a-step-by-step-on-how-it-works-307592). In general, there is no pattern for this.  This commercial crawler (https://www.screamingfrog.co.uk/seo-spider/faq/) uses the domain as entry for the queue, just like this one (https://scrapy-cluster.readthedocs.io/en/latest/topics/introduction/overview.html).
 
In google's robots.txt specification (https://developers.google.com/search/reference/robots_txt), the robots file is valid for a specific domain, but not for the subdomain. Yet in the documentation, it is possible to notice the following:

```
Valid for http://212.96.82.21/

Invalid for: http://example.com/ (even if it is hosted on 212.96.82.21) 
```
What lead to the conclusion that the bot uses the domain in the url, not the ip.

**Comment by gsjunior86** [comment]
implemented in branch https://github.com/dice-group/Squirrel/tree/feature/domain-based-queue
