### ISSUE TITLE
Regex in HtmlScrapper doesn't actually check for regular expression

### ISSUE THREAD

**Issue by sritejakv** [dice-group/Squirrel#107]
In Line, https://github.com/dice-group/Squirrel/blob/f5e798c50af231fd47f73907bb5b6c64251897b3/squirrel.worker/src/main/java/org/dice_research/squirrel/analyzer/impl/html/scraper/HtmlScraper.java#L135

There is a check for regex specified in yaml files. But it is a check to find if the string is present in the given URL. In such case, while specifying a yaml rule for an index page of a data portal, the rule works for each and every page as the index page regex would be given as '/'.

**Comment by gsjunior86** [comment]
I will consider the same yaml file used in issue #108

**Comment by gsjunior86** [comment]
the indentation was wrong and the logic to capture the context it was inefficient also. Check issue #108
