### ISSUE TITLE
Check if graph exists, before sending triples to SparqlEndpoint

### ISSUE THREAD

**Issue by gsjunior86** [dice-group/Squirrel#112]
In the SparqlSink, it is necessary the check if the graph exists before updating. If it is not, create a graph, according to SPARQL 1.1 especification

**Comment by MichaelRoeder** [comment]
https://www.w3.org/TR/2013/REC-sparql11-update-20130321/#create

**Comment by gsjunior86** [comment]
This issue is related with Bland Nodes insertion with SPARQL 1.1 on virtuoso7, which allows Blank Nodes only if the graph already exists (this problem does not happen on Fuseki).

It is solved based on this comment : https://github.com/openlink/virtuoso-opensource/issues/126#issuecomment-66315349, adding the where clausule with { SELECT * {OPTIONAL {?s ?p ?o} } LIMIT 1 }
