### ISSUE TITLE
Improve seed file reader

### ISSUE THREAD

**Issue by MichaelRoeder** [dice-group/Squirrel#114]
## Description

As a user, I would like to provide additional information for seed files, e.g., the type of a URI or some other data that could improve its processing. Therefore, the reader for the seed file should be improved to be able to process this additional information.

## Solution
* To keep the solution general, it would be good if the reader would accept a CSV file with a head line which defines the keys for the values. In the following example `uri` is used to mark the column with the URIs while the other columns contain additional data which should be added to the URIs object.
```
"uri","key1","key2"
"http://example1.org","value1-1","value1-2"
"http://example2.org","","value2-2"
"http://example3.org",,
```
* Note that `""` should be used as an empty value, i.e., the key should be added with an empty string as value.
* Note that the key value pair (or the key with an empty value) should only be added if the cell is _not_ empty. The line of `"http://example3.org"` contains two empty cells which should make sure that both keys are not added to this URI.

**Comment by MichaelRoeder** [comment]
Add a JUnit test for this seed file reader and close #14 after that.

**Comment by gsjunior86** [comment]
pushed on **develop** branch
