### ISSUE TITLE
Handle common archive files

### ISSUE THREAD

**Issue by MichaelRoeder** [dice-group/Squirrel#34]
## Description

The crawler has to be able to handle dump files. However, the newly added HTTPFetcher replaced the DumpFileFetcher. Now, there is no step that takes care of extracting an archive file that has been downloaded.

## Solution
Provide the extraction of the following common file formats:
- [x] `*.zip`, `.zipx` (`application/zip`)
- [x] `*.gz` (`application/gzip`)
- [x] `*.tar` (`application/x-tar`)
- [x] `*.tar.gz`, `*.tgz` (`application/x-gtar`)
- [x] `*.bz2` (`application/x-bzip2`)
- [x] `*.tar.bz2`, `*.tbz2` (`application/x-gtar`)

Note that the archive might contain more than one file. This leads to a situation in which the Worker might have to call the Analyzer either several times (once for every file) or the semantic of the Analyzer's API has to be changed to accept a file that points to a directory containing several files.

* It should be implemented in a way that new extractors (e.g., for `*.rar`) can be added easily.
* http://commons.apache.org/proper/commons-compress/ might be helpful to handle other compressions than GZip (which is supported by `jav.utils`)

**Comment by gsjunior86** [comment]
commited to develop
