### ISSUE TITLE
Make sure the Travis integration is working

### ISSUE THREAD

**Issue by MichaelRoeder** [dice-group/Squirrel#35]
We have a continous integration platform (Travis) that is building the project and executing the tests every time changes are pushed to the project. However, at the moment this fails because the `org.aksw.simba.squirrel.analyzer.impl.AnalyzerTest` is started but does not make any progress within 10 minutes (https://travis-ci.org/dice-group/Squirrel). This needs to be fixed.

**Comment by gsjunior86** [comment]
next() was not been called in the test

**Comment by gsjunior86** [comment]
next() was not been called in the test
