### ISSUE TITLE
Enable Simple Recrawling 

### ISSUE THREAD

**Issue by IVIerle** [dice-group/Squirrel#47]
Implement a simple mechanism which allows re-crawling when fetching data from an URI fails. 
If the fetcher throws an Exception, readd the URI to the queue to try again later (possibly with a delay or definition of the re-crawl time). 

This would help immensely in dealing with frequent Socket Timeout Exceptions when fetching data from the mCloud.
Something simple would suffice until the recrawling component is done.

**Comment by MichaelRoeder** [comment]
Fixed in the `simpleRecrawling` branch.
