### ISSUE TITLE
Dataset Versioning

### ISSUE THREAD

**Issue by IVIerle** [dice-group/Squirrel#48]
## Description

To be able to identify changes and additions to the data stored by a Sink, it would be great to have some sort of dataset versioning in addition to the crawl timestamps. 

A step of comparing the newly crawled and the old data would be nice, so we only need to store the graph if it has been updated, else just set the new crawl time to the old one.
**Micha**: deduplication is already planned but won't be part of this issue. We should get it during the next 2-3 months.

## Solution

- [x] The Worker should generate a URI for its current activity to crawl a certain, given URI
    - [x] this URI could be `cUri.getUri().toString() + '_' + System.currentTimeMillis()` (where cUri is the crawleable URI that is handled at the moment)
    - [x] this URI should be add to the data of the crawleable URI and a constant in the Constants class should be added, e.g., `URI_CRAWLING_ACTIVITY_URI="activity-uri"`
    * This URI could be used for the crawling activity in the meta data (provenance!)
- [x] Every sink should use the value of `URI_CRAWLING_ACTIVITY_URI` if it is present in the data of the given URI. If not, the URI itself can be used (as it is done at the moment)

**Comment by MichaelRoeder** [comment]
Updated the description.

**Comment by gsjunior86** [comment]
@MichaelRoeder , i updated the FileBased sink testing if the URI_CRAWLING_ACTIVITY_URI is present.
