### ISSUE TITLE
Add feature to define a URI Whitelist

### ISSUE THREAD

**Issue by IVIerle** [dice-group/Squirrel#49]
## Description

As a user, I would like to be able to define a whitelist containing URIs that are allowed to be crawled. All other URIs should be ignored. The implementation should be based on regular expressions which are defined in a file defined by the user.

## Solution
- [ ] Define a class `RegexBasedWhiteListFilter` 
    - [ ] that is implementing the `UriFilter` interface
    - [ ] that is created with a list of Strings which are interpreted as regular expressions
    - [ ] which are used in the `isUriGood` method. The method should return true if one of the regular expressions matches the URI.
    - [ ] Add a JUnit test for this class.
- [ ] Extend the `FrontierImpl` class
    - [ ] by adding an additional (optional) `UriFilter` which is used to check all added URIs (in addition to the `KnownUriFilter`)
    - [ ] in line https://github.com/dice-group/Squirrel/blob/master/src/main/java/org/aksw/simba/squirrel/frontier/impl/FrontierImpl.java#L111 by using the additional UriFilter (if present) to check the added URI
- [ ] Extend the https://github.com/dice-group/Squirrel/blob/master/src/main/java/org/aksw/simba/squirrel/components/FrontierComponent.java class to check the environment for, e.g., `URI_WHITELIST_FILE`, load its content (if present), create a `RegexBasedWhiteListFilter` instance and add it to the `FrontierImpl` instance.

**Comment by MichaelRoeder** [comment]
Updated description

**Comment by gsjunior86** [comment]
Commited to develop
you can use the **org.aksw.simba.squirrel.components.WhiteListFrontierComponent** as argument in the Frontier Launcher. If the URI_WHITELIST_FILE env is present, will load the RegexBasedWhiteListFilter. If not, the RDBKnownUriFilter will be loaded. The RegexBasedWhiteListFilter extends the RDBKnownUriFilter with the isUriGood overrided to check if contains in the whitelist.
