### ISSUE TITLE
WorkerComponent adding and retrieving URIs

### ISSUE THREAD

**Issue by IVIerle** [dice-group/Squirrel#51]
When loading new URIs to crawl from the frontier (in this case WorkerComponent.getNextUris()) the 'data' map of the CrawleableUri is always empty.  
Even though 'data' had entries when entering WorkerComponent.addNewUris(...) right before sending to the RabbitQueue, those entries are all gone after deserialization. 
Not sure if this might have something to do with the BasicProperties.Builder.

**Comment by gsjunior86** [comment]
@IVIerle , could you post your seeds please, because i'm not finding any uri that comes with "data" entries. Thx!

**Comment by MichaelRoeder** [comment]
Maybe it is easier if @IVIerle provides an example that we can use for "simulating" it? We could have a manipulated worker that sends this URI object to the Frontier, request the next set of URIs and checks whether the worker receives the URI with the data attached or not... :thinking: just an idea :wink:

**Comment by gsjunior86** [comment]
@MichaelRoeder , yes, better that way, thank you :)

**Comment by IVIerle** [comment]
Hey Geraldo, 
this is a peculiarity of the analyzer i am writing. As i am basically html-scraping a website it very much matters to me which site exactly i am trying to parse at the moment.
I enter it with the seed ( https://www.mcloud.de/web/guest/suche/ ) and the analyzer extracts some new URIs that i add some 'data' to and then add the URIs to the queue.  
My analyzer decides which method to invoke on  an URI based on the availability of certain data map entries, so i need those to survive the cycle through the frontier. 
Later on i also add metadata to the datamap that in some cases i want to pass down, so it is really important to me that all entries i added at some point are available. 

You could very much test this as Michael suggested, just instantiate a new CrawleableUri, add some random entry to the data map and add it to the frontier with addNewUris. 
The data has to still be available after getting the uri from the frontier queue with getNextUris.
Sorry for the late answer :)

**Comment by gsjunior86** [comment]
Hi @IVIerle , sorry for the late answer. We found later a problem with the SqlBasedURICollector that was returning only onde URI. I have teste the serialization, setting data hardcoded inside the toString in GzipSerializer and all the data was returned ok in the nextUris() method.

**Comment by IVIerle** [comment]
Hey @gsjunior86, 
yes is was aware of that error but Micha fixed it last week for me. I'll try again with the serialization after the changes and get back to you

**Comment by IVIerle** [comment]
Unfortunately the error still persists. I truncated the log file to exemplify the way of a particular URI ("https://www.mcloud.de/web/guest/suche/-/results/search/0"). I printed the length of the data map and 
'Search = boolean - Detail = boolean - Resource = boolean' shows whether data.containsKey() returns true for a key i've added.

[uri0.log](https://github.com/dice-group/Squirrel/files/1756022/uri0.log)
 
[WorkerComponent]
As you can see in line 12 the data map has 1 entry (the search related one) before calling sender.sendData(serializer.serialize(new UriSet(uris)));
Then line 21 shows that after (UriSet) serializer.deserialize(response); 
there are not entries in the data map any longer. 

I still do not know exactly what the problem is, it could have been the serializer (but you seem to have tested that) but also the rabbit DataSenderImpl. As i mentioned could it maybe have something to do with the BasicProperties that filter out my keys? 
May i ask which key and value exactly you added to the dataset that you got back successfully, was it an arbitrary one or a known one? 
I really need to work this out to be able to finish my work, thanks :)

**Comment by gsjunior86** [comment]
Hi @IVIerle .

in the WorkerComponent@addNewUris, for every uri sent to the serializer, i added a simple entry ("TEST","123"). Later, in the getNextUris method, it was possible to retrieve this simple entry in every uri.

Which serializer are you using? I think that there was a problem which gson serializing not preserving map entries.

**Comment by IVIerle** [comment]
Hey @gsjunior86, 

i did not manipulate the Serializer, so it should be the GzipJavaUriSerializer that is initialized in the WorkerComponent constructor. 
The data is right there in WorkerComponent@addNewUris before calling sender.sendData so if you added hardcoded entries there i don't get why it doesn't work for me (i tried hard coding it there, it makes no difference). You said you hardcoded it into the serializer.toString before. 
All URIs in the UriSet after deserializing the response have no data entries whatsoever.

**Comment by gsjunior86** [comment]
@IVIerle , i reproduced the problem here.

**Comment by IVIerle** [comment]
Hey @gsjunior86, 

i did not manipulate the Serializer, so it should be the GzipJavaUriSerializer that is initialized in the WorkerComponent constructor. 
The data is right there in WorkerComponent@addNewUris before calling sender.sendData so if you added hardcoded entries there i don't get why it doesn't work for me (i tried hard coding it there, it makes no difference). You said you hardcoded it into the serializer.toString before. 
All URIs in the UriSet after deserializing the response have no data entries whatsoever.

**Comment by gsjunior86** [comment]
@IVIerle , the RDBQueue was sending only the the uri as string to the RethinkDB. I wrote a temporary solution (serializing a Crawleable uri object and arrying bytes in a string) because the previous solution was developed with String storage in mind, but will improve this in an enhancement. Please test in your needs and post your feedback.
