### ISSUE TITLE
Replace RethinkDB

### ISSUE THREAD

**Issue by MichaelRoeder** [dice-group/Squirrel#65]
## Description

Since RethinkDB has issues which can not be solved easily (#61) we would like to have another storage that can be used instead.

## Solution
- [x] Implement a KnownUriFilter based on another, persistent storage solution
- [x] Implement an IPBasedQueue based on another, persistent storage solution
- [x] Include both into the docker-compose file, replacing RethinkDB

**Comment by gsjunior86** [comment]
The KnowUriFilter and IPBasedQueue were implemented and all the tests are ok.
