### ISSUE TITLE
Restructure project

### ISSUE THREAD

**Issue by MichaelRoeder** [dice-group/Squirrel#74]
## Description

As a developer of Squirrel, I would like to have multiple, light weight projects instead of one monolytical project.

## New structure

The following sub modules should be created

* squirrel.api - central classes needed by the frontier and the worker
* squirrel.deduplication - everything needed for the deduplication
* squirrel.frontier - everything needed for the frontier container
* squirrel.mockup - mockups mainly used for testing
* squirrel.web - everything needed for the web demo container
* squirrel.web-api - central classes needed for the communication between the frontier and the web demo
* squirrel.worker - everything needed for the worker

## Necessary actions
- [x] Create parent pom
- [x] Create projects
- [x] Move classes into projects in a way that git can recognize the movement!
- [x] Introduce new package names (`org.dice_research` instead of `org.aksw.simba` or `com.*`)
- [x] Adapt build procedure (creation of Docker images, image names, docker-compose files, etc.)
- [x] Remove unnecessary files

**Comment by MichaelRoeder** [comment]
@gsjunior86 Could you please check whether the last two points are solved? (i.e., build process and removal of files)

**Comment by gsjunior86** [comment]
@MichaelRoeder ,sure, i'll check it out
