### ISSUE TITLE
Improve integration of the Any23 library

### ISSUE THREAD

**Issue by MichaelRoeder** [dice-group/Squirrel#91]
## Description

At the moment, the microdata parser uses the Any23 library to extract triples. However, the usage of the library is implemented in a way that creates an additional effort since it contains an unnecessary transformation of triples into N-Triples:
```
html String -> html in-memory objects -> triples -> N-Triples -> triples -> sink / collector
```
This should be eased to
```
html String -> html in-memory objects -> triples -> sink / collector
```
by implementing the [`TripleHandler`](https://github.com/apache/any23/blob/master/api/src/main/java/org/apache/any23/writer/TripleHandler.java) interface.

## Solution
- [x] Implement a [`TripleHandler`](https://github.com/apache/any23/blob/master/api/src/main/java/org/apache/any23/writer/TripleHandler.java) which is able to transform the incoming triples into the form needed by the UriCollector and the sink.
- [x] The handler should be able to forward the triples to both - UriCollector and TripleBasedSink instances.
- [x] Use this newly implemented class in the parser

**Comment by gsjunior86** [comment]
org.dice_research.squirrel.analyzer.commons.SquirrelTripleHandler is implemented, using UriCollector and Sink to store triples directly.
