### ISSUE TITLE
Improve the Semargl integration

### ISSUE THREAD

**Issue by MichaelRoeder** [dice-group/Squirrel#92]
## Description

At the moment, the integration of the Semargl parser is integrated by writing its output into a character stream which is parsed after that by Jena (see https://github.com/dice-group/Squirrel/blob/master/squirrel.worker/src/main/java/org/dice_research/squirrel/analyzer/impl/RDFaSemarglParser.java#L57).
However, this can be improved by using the Jena integration of Semargl (see https://github.com/semarglproject/semargl-jena)

**Comment by gsjunior86** [comment]
created a TripleSink for it.
